== Recipes for data consumers

=== Search the Global Discovery Catalogue

The https://wmo-im.github.io/wis2-guide/guide/wis2-guide-APPROVED.html#_2_4_4_global_discovery_catalogue[Global Discovery Catalogue (GDC)] allows for a wide range of query predicates to search for data in WIS2 as per the OGC API - Records - Part 1: Core specification.

The GDC can be searched via the `/collections/wis2-discovery-metadata/items` endpoint.  This endpoint provides a number query parameters as described in the examples below.

**NOTE**: examples below are not URL encoded for clarity / readability, but should be when interacting with the GDC.

==== Spatial queries

- search for metadata records of data in Canada: `bbox=-142,42,-52,84`

Note that the format of `bbox` is comma-separated values in the following order:

- minimum longitude
- minimum latitude
- maximum longitude
- maximum latitude

==== Temporal queries

- search for metadata records updated since 29 July 2024: `datetime=2024-07-29/..`
- search for metadata records updated before 29 July 2024: `datetime=../2024-07-29`
- search for metadata records updated on 29 July 2024: `datetime=2024-07-29`

==== Equality queries

- search for metadata records whose title contains the terms hourly observations: `title=hourly observations`
- search for metadata records whose title contains the terms hourly or observations: `title=hourly | observations`
- search for metadata records for a specific contact organization `contacts.organization=Direction Generale de la Météorologie`

==== Freetext search

- search metadata records for temperature: `q=temperature`
- search metadata records for GRIB2 data: `q=GRIB2`
- search metadata records for any GRIB data: `q=\*GRIB*`
- search metadata records for any GRIB data in Germany: `q=\*GRIB* AND germany`
- search for either GRIB data or data in Europe with subscriptions to the Météo-France Global Broker: `q=(\*GRIB* OR \*Europe*) AND \*globalbroker*`
- search for data from Belize with MQTT subscription capabilities: `q="cache/a/wis2/bz-nms"`

==== Sorting

- sort search results by title, ascending: `sortby=title`
- sort search results by title, descending: `sortby=-title`

==== Paging

- present search results 1-10: `limit=10`
- present search results 11-20: `limit=10&offset=10`
- limit to 3 search results: `limit=3`

=== Finding data subscription services from the Global Discovery Catalogue

The https://wmo-im.github.io/wis2-guide/guide/wis2-guide-DRAFT.html#_2_4_4_global_discovery_catalogue[Global Discovery Catalogue (GDC)] contains both real-time and non real-time data.  The https://wmo-im.github.io/wcmp2/standard/wcmp2-STABLE.html[WMO Core Metadata Profile (WCMP2)] allows for description of real-time data via its https://wmo-im.github.io/wcmp2/standard/wcmp2-STABLE.html#_1_19_links_and_distribution_information[distribution information], which data publishers use to describe and define connectivity and subscription information for a given dataset.

A typical WCMP2 distribution link for data subscriptions can be found below:

[source,json]
----
{
    "rel": "items",
    "href": "mqtts://everyone:everyone@globalbroker.meteo.fr:8883",
    "channel": "origin/a/wis2/ca-eccc-msc/data/core/hydrology",
    "type": "application/geo+json",
    "title": "Data notifications"
}
----

Programatically, a GDC client can query the catalogue and filter the results for real-time subscriptions in the following manner:

[source,python]
----
import requests

response = requests.get('https://wis2-gdc.weather.gc.ca/collections/wis2-discovery-metadata/items').json()


def is_wis2_subscription_link(link) -> bool:
    if (link['href'].startswith('mqtt') and 
            link.get('channel', '').startswith(('origin/a/wis2', 'cache/a/wis2'))):
        return True


for feature in response['features']:
    for link in feature['links']:
        if is_wis2_subscription_link(link):
            print('WIS2 subscription link')
----

Using the `href` and `channel` properties of a matching link object, a client can connect and subscribe to data notifications for a given dataset.
