=== Best practices for publishing station based observational data

The WMO Unified Data Policy defines the following data types:

* Core Weather Surface-based data: observations provided by the Global Basic Observing Network (GBON) and other observational data, as specified in the Manual on the WMO Integrated Global Observing System (WMO-No. 1160);
* Recommended Weather Surface-based data: all available observations provided by the Regional Basic Observing Network (RBON), which is further specified in the Manual on the WMO Integrated Global Observing System (WMO-No. 1160);
* Core Climate observational data
** Measurements provided by the Global Climate Observing System (GCOS) Upper-Air Network (GUAN) and GCOS Surface Network (GSN) stations (see also 1.1.1 (a));
** Climate data as defined in the Manual on High-quality Global Data Management Framework for Climate (WMO-No. 1238);
** Essential Climate Variables (ECVs) as defined by the GCOS in the Manual on the WMO Integrated Global Observing System (WMO-No. 1160) to the extent that the Member holds the data in a digital archive

Typically, observational data is published using BUFR as the representation/format, as specified in the Manual on Codes (WMO-No. 306). The Manual on the Global Telecommunication System (WMO-No 386) mandates the provision of the data as a "bulletin" (multiple observational data grouped into a single BUFR file).

It is considered that with modern telecommunication protocols, the "bulletin" approach is no longer required. Therefore, in the WIS 2.0 context, the "bulletin" approach is deprecated and observational data should be provided as individual BUFR files without grouping.

As publishing data to WIS 2.0 requires the WIS 2.0 Notificiation Message (WNM), the following aspects should be included when publishing observational data.

==== Geometry

WNM requires a `geometry` property, which allows for expressing the location of a data granule (in this case a BUFR file) as follows:

[source,json]
----
{
  "geometry": {
    "type": "Point",
    "coordinates": [-87.42188, 44.83941, 712]
}
----

Note that the order of the geometry coordinates are longitude, latitude and elevation.  In addition, when a geometry cannot be provided, `geometry` can be set to `null`.

==== Client Side Filtering

WNM allows for extensibility (i.e. adding additional properties) by design.  To enable client side filtering, and when the WIGOS Station Identifier (WSI) exists for observational data, a WNM should include `properties.wigos_station_identifier` as follows:

[source,json]
----
{
  "properties": {
    "wigos_station_identifier": "0-20000-0-71628"
  }
}
----

By providing geometry and WIGOS station identifier in a WNM for observational data, this allows for users to assess and filter WIS 2.0 notifications using location and WSI as the filter criteria.

For more information on client side filtering see recipe <<_advertising_client_side_filters_for_data_subscriptions_in_wcmp2_and_wnm>>.
